### PR TITLE
Issue/#6

### PR DESCRIPTION
**Pull request by Masynchin**

### CODE REVIEW

**Comment by Masynchin** [comment]
I have struggled a bit with trying to implement `IntegerAsText` as decorator envelope, but here we are:


~~~kotlin
class IntegerAsText(source: Entity) : EntityWrap(Entity { Text(BigInteger(source.dataize()).toString()).dataize() })
~~~

I am asking for two way of improvement:

1) In terms of Kotlin. Is this correct way of using [functional interface](https://kotlinlang.org/docs/fun-interfaces.html)?
2) In terms of logic. Dataization happens two times, let me know if this amount can be reduced.

**Comment by kerelape** [comment]
@Masynchin looks great! Just add `Number#asText` extensions and it's done

**Comment by kerelape** [comment]
> I have struggled a bit with trying to implement `IntegerAsText` as decorator envelope, but here we are:
> 
> ```kotlin
> class IntegerAsText(source: Entity) : EntityWrap(Entity { Text(BigInteger(source.dataize()).toString()).dataize() })
> ```
> 
> I am asking for two way of improvement:
> 
> 1. In terms of Kotlin. Is this correct way of using [functional interface](https://kotlinlang.org/docs/fun-interfaces.html)?
> 2. In terms of logic. Dataization happens two times, let me know if this amount can be reduced.

You only dataise each entiy once - it's alright

**Review by kerelape — APPROVED** [review]

**Comment by Masynchin** [comment]
Should I use `IntegerAsText` for out type, or `Entity`?

~~~kotlin
val Number.asText: IntegerAsText/Entity
    get() = IntegerAsText(this.asEntity)
~~~

**Comment by kerelape** [comment]
> I have struggled a bit with trying to implement `IntegerAsText` as decorator envelope, but here we are:
> 
> ```kotlin
> class IntegerAsText(source: Entity) : EntityWrap(Entity { Text(BigInteger(source.dataize()).toString()).dataize() })
> ```
> 
> I am asking for two way of improvement:
> 
> 1. In terms of Kotlin. Is this correct way of using [functional interface](https://kotlinlang.org/docs/fun-interfaces.html)?
> 2. In terms of logic. Dataization happens two times, let me know if this amount can be reduced.

In terms of Kotlin, there is no other way to do this as far as I know, you can do like `EntityWrap { 
... }` but not in context of implementation

**Comment by kerelape** [comment]
@rultor merge

**Comment by Masynchin** [comment]
> @rultor merge

I didn't add Number.asText 😭.

**Pull request merged**
