### PR TITLE
Issue/#60

### PR DESCRIPTION
**Pull request by Masynchin**

### CODE REVIEW

**Comment by Masynchin** [comment]
@kerelape will it close #59 without explicit "Close #59"?

**Review by kerelape — APPROVED** [review]

**Comment by kerelape** [comment]
> @kerelape will it close #60 without explicit "Close #60"?

@Masynchin I hope so

**Review by kerelape — CHANGES_REQUESTED** [review]
Please use `EntityWrap` for classes that only have `dataize` method

**Comment by Masynchin** [comment]
@kerelape I would rewrite using `EntityWrap` once Xor will be in binary module, so I can rewrite all of them in one PR.

**Review by kerelape — APPROVED** [review]

**Comment by kerelape** [comment]
@rultor merge

**Comment by kerelape** [comment]
@Masynchin thank you!

**Pull request merged**
