### PR TITLE
Issue/#7

### PR DESCRIPTION
**Pull request by Masynchin**
Add Sprintf and its tests. This is correct docs referring to?

> So for now simply treat every arg as an Entity of text (and don't forget to mention in the doc)

### CODE REVIEW

**Comment by Masynchin** [comment]
@kerelape in order to use Sprintf here

https://github.com/kerelape/reikai/blob/a4ea7f8cc2f9ec4cc99dd99ab225c96646a43735/src/main/kotlin/me/kerelape/reikai/io/network/TcpEndpoint.kt#L19-L26

This todo should be solved #6.

**Comment by Masynchin** [comment]
@kerelape can we remove this temp variables?

~~~kotlin
val template = String(this.template.dataize())
val args = this.args.map { String(it.dataize()) }
return Text(template.format(*args.toTypedArray())).dataize()
~~~

If I add secondary constructors, then entities would dataize too soon. Is there are something like Scalar or Scala `lazy val`?

**Comment by kerelape** [comment]
> 

@Masynchin Kotlin has `lazy`, but we should not use it here, because there should not be any fields created inside class and not passed via contructor. Of cource this rule cannot be applied everywhere but we should try applying it. The code above looks totally fine with the variables.

**Comment by Masynchin** [comment]
Wrong time for reviewing, #6 still unresolved.

**Comment by kerelape** [comment]
> Wrong time for reviewing, #6 still unresolved.

This can be resolved later. Remove the TODO related to this issue and make use of `Sprintf` as is. Since `Entity` is a functional interface, you can temproary use `Entity { BigInteger(...).toString().toByteArray() }`

**Review by kerelape — DISMISSED** [review]

**Comment by Masynchin** [comment]
> `Entity { BigInteger(...).toString().toByteArray() }`

I use `Text(BigInteger(this.port.dataize()).toString())` instead. Should be same, right?

**Review by kerelape — DISMISSED** [review]

**Comment by kerelape** [comment]
@rultor merge

**Comment by kerelape** [comment]
@rultor merge, please

**Comment by kerelape** [comment]
@Masynchin I'll try to figure out why the error happened tomorrow

**Comment by Masynchin** [comment]
Maybe it is because of my merge commit?

**Comment by kerelape** [comment]
@rultor merge

**Pull request merged**
