### PR TITLE
Simplify Group

### PR DESCRIPTION
**Pull request by Masynchin**
Tests are fine.

Can in Kotlin I write something like this?

~~~kotlin
items
    .map { it.dataize() }
    .reduce ByteArray::plus
~~~

Or this? 🤨

~~~kotlin
items.foldMap Entity::dataize
~~~

### CODE REVIEW

**Comment by kerelape** [comment]
@rultor merge

**Comment by kerelape** [comment]
@rultor merge

**Comment by kerelape** [comment]
@Masynchin thank you for your help!

**Comment by Masynchin** [comment]
@kerelape what can you say code snippets in my first comment?

**Comment by kerelape** [comment]
> @kerelape what can you say code snippets in my first comment?

@Masynchin you write it like this: `item.map(Entity::dataize).reduce(ByteArray::plus)`

**Comment by kerelape** [comment]
> > @kerelape what can you say code snippets in my first comment?
> 
> @Masynchin you write it like this: `items.map(Entity::dataize).reduce(ByteArray::plus)`

@Masynchin but it only works because `ByteArray#plus` is an extension function, and it is compiled like this: `fun ByteArray.plus(other: ByteArray): ByteArray` -> `
fun plus(thisRef: ByteArray, other: ByteArray): ByteArray
`
which matches the signature of the lambda `reduce` takes

**Pull request merged**
