### PR TITLE
Add Boolean.asEntity

### PR DESCRIPTION
**Pull request by Masynchin**
With this changes I also add tests for True/False.

### CODE REVIEW

**Comment by Masynchin** [comment]
@kerelape tests fails. Why?

**Comment by kerelape** [comment]
@Masynchin you check equality of arrays - on JVM these are not equal because they have different addresses in the memory.

You can fix it this way: `n.dataize()` -> `n.dataize()[0].toByte()`

**Review by kerelape — APPROVED** [review]

**Review by kerelape — CHANGES_REQUESTED** [review]
Change to
```kotlin
Assertions.assertEquals(
    true.asEntity.dataize()[0],
    True.dataize()[0]
)
```

**Review by kerelape — APPROVED** [review]

**Comment by kerelape** [comment]
@rultor merge

**Comment by kerelape** [comment]
@Masynchin thank you, your work is highly appreciated

**Pull request merged**
