### PR TITLE
Test for false against bytearray of zeros

### PR DESCRIPTION
**Pull request by Masynchin**
Reflect [this](https://github.com/kerelape/reikai/issues/42#issuecomment-1193280751) in tests.

### CODE REVIEW

**Comment by Masynchin** [comment]
@kerelape IntelliJ automatically puts `import io.github.kerelape.reikai.core.Data` to the top of imports. I think in Kotlin (same as in Python, Go, and bunch of other languages I am more familiar with) kotlin/java imports came first, then third-party, and lastly first-party. Am I right? If yes, how can I setup my IntelliJ so imports added in correct order?

**Comment by kerelape** [comment]
@Masynchin imports have to be sorted alphabetically. [This](https://stackoverflow.com/questions/59354430/how-to-sort-imports-in-alphabeticall-order-in-intellij) can help you to setup your IDE

**Comment by Masynchin** [comment]
> @Masynchin imports have to be sorted alphabetically.

So, IntelliJ put import at right place? Then, in [this file](https://github.com/kerelape/reikai/blob/a7192fe9c4fc2d5e0171cb893e25574799fc6402/src/main/kotlin/io/github/kerelape/reikai/io/network/TcpEndpoint.kt) they are in wrong order. #35.

> [This](https://stackoverflow.com/questions/59354430/how-to-sort-imports-in-alphabeticall-order-in-intellij) can help you to setup your IDE.

Thanks a lot!

**Comment by kerelape** [comment]
@rultor merge

**Pull request merged**
